accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

ulrpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('<str:username>', views.profile, name='profile'),
    path('<str:username>/follow', views.follow, name='follow'),
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/like', views.like, name='like'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField

# Create your models here.
class User(AbstractUser):
    profile_image = ResizedImageField(
        size=[500, 500],
        crop=['middle', 'center'],
        upload_to='profile',
    )
    # post_set = 
    # like_posts =

    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings

# Create your models here.
class Post(models.Model):
    context = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ResizedImageField(
        size=[500, 500],
        crop=['middle', 'center'],
        upload_to='image/%Y?%m'
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # user_id =

    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'profile_image',)


class CustomAuthenticationForm(AuthenticationForm):
    pass

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('user', 'like_users',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required


# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:index')

    else:
        form = CustomUserCreationForm

    context = {
        'form' : form,
    }

    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('posts:index')

    else:
        form = CustomAuthenticationForm
    
    context = {
        'form' : form,
    }

    return render(request, 'accounts/form.html', context)


def profile(request, username):
    User = get_user_model()
    user_info = User.objects.get(username=username)

    context = {
        'user_info' : user_info,
    }

    return render(request, 'account/profile.html', context)

@login_required
def follow(request, username):
    User = get_user_model()

    me = request.user
    you = User.objects.get(username=username)

    # 내가 이미 너를 팔로우했는데 눌렀다면
    if me in you.follower.all():
        me.followings.remove(you)

    # 아직 내가 너를 팔로우 하지 않았다면
    else:
        me.followings.add(you)

    return redirect('accounts:profile', username=username)

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    posts = Post.objects.all().order_by('-id')

    context = {
        'posts' : posts,
    }

    return render(request, 'index.html', context)



def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('post:index')

    else:
        form = PostForm()

    context = {
        'form' : form,
    }

    return render(request, 'form.html', context)


@login_required
def comment_create(request, post_id):
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)

        # 현재 로그인 유저
        comment.user = request.user
        # post_id를 기준으로 찾은 post
        post = Post.objects.get(id=post_id)
        comment.post = post

        # comment.post_id = post_id

        comment.save()

        return redirect('posts:index')


@login_required
def like(request, post_id):

    # 좋아요 버튼 누른 유저
    user = request.user
    post = Post.objects.get(id=post_id)

    # 이미 좋아요 버튼 눌렀다면
    if post in user.like_posts.all():
        post.like_users.remove(user)

    # 아직 좋아요 버튼 안 눌렀다면
    else:
        post.like_users.add(user)

    return redirect('posts:index')

accounts/templates/accounts/form.html
{% extends 'base.html %}
{% load bootstrap5 %}
{% block body %}

<form action="" method="POST" enctype="multipart/form-data">
    <h1>signup</h1>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">


</form>


{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block body %}

<div class="row">
    <div class="col-4">
        <img src="{{user_info.profile_image.url}}" alt="" class="img-fluid rounded-circle">
    </div>
    <div class="col-8">
        <div class="row">
            <div class="col-3">{{user_info.username}}</div>
            {% if user != usr_info %}
            <div class="col-4">
                {% of user in user_info.followers.all %}
                    <a href="{% url 'accounts:follow' username=user_info.username %}" class="btn btn-secondary btn-sm">팔로잉</a>
                {% else %}
                    <a href="{% url 'accounts:follow' username=user_info.username %}" class="btn btn-secondary btn-sm">팔로우</a>
                {% endif %}
            </div>
            {% endif %}
        </div>
        <div class="row">
            <div class="col">게시물 {{user_info.post_set.all|length}}</div>
            <div class="col">팔로워 {{user_info.followers.all|length}}</div>
            <div class="col">팔로우 {{user_info/followings.all|length}}</div>
        </div>
    </div>
</div>

<div class="row-row-cols-3">
    {% for post in user_info.post_set.all %}
        <div class="col">
            <div class="card">
                <img src="{{post.image.url}}" alt="">
            </div>
        </div>
    {% endfor %}
</div>


{% endblock %}

posts/templates/_card.html
{% load bootstrap5 %}
<div class="card mt-4" style="width: 18rem;">
    <div class="card-header">
        <p>
            <img src="{{post.user.profile_image.url}}" alt="" class="rounded-circle" width="50px">
            <a href="{% url 'accounts:profile' username=post.user %}" class="text-reset text-decoration-none">{{post.user}}</a>
        </p>
    </div>
    <img src="{{post.image.url}}"  alt="...">
    <div class="card-body">
        <!-- <h5 class="card-title">Card title</h5> -->
        <a href="{% url 'posts:like' post_id=post.id %}" class="text-reset text-decoration-none">
            {% if post in user.like_posts.all %}  
            <i class="bi bi-suit-heart-fill" style="color:red"></i>
            {% else %}
            <i class="bi bi-suit-heart"></i>
            {% endif %}
        </a> {{post.like_users.all|length}} 명이 좋아합니다.

        <p class="card-text">{{post.content}}</p>
        <p class="card-text">{{post.created_at|timesince}}</p>
        <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
    </div>
    <div class="card-footer">
        {% if user.is_authenticated %}
        <form action="{% url 'posts:comment_create' post_id=post.id %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <input type="submit">
        </form>
        <hr>
        {% endif %}

        {% for comment in post.comment_set.all %}
            <li>{{comment.user}} : {{comment.content}}</li>
        {% endfor %}
    </div>
</div>

posts/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>

{% endblock %}

posts/templates/index.html
{% extends 'base.html' %}

{% block body %}

    {% for post in posts %}
        {% include '_card.html' %}

    {% endfor %}

{% endblock %}

<!-- template tag : django에서 사용가능한 형식 -->

templates/_nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'posts:index' %}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'posts:create' %}">Create</a>
          <a class="nav-link" href="{% url 'accounts:profile' username=user %}">{{request.user}}</a>
          {% else %}
          <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
          <a class="nav-link" href="{% url 'accounts:login' %}" >Login</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    {% include '_nav.html' %}

    <div class="container">
        {% block body %}
        {% endblock %}

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

</body>
</html>